blockExoticSubdeps: true
enablePrePostScripts: false
ignorePatchFailures: false
optimisticRepeatInstall: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
verifyDepsBeforeRun: install
